### ISSUE TITLE
Getting error while parsing in target_nf_type and requester_nf_type

### ISSUE THREAD

**Issue by sohel1119** [H21lab/5GC_build#11]
While parsing the code in we encountered an error where target_nf_type is showing error
Exactly what should be set/define in the target_nf_target and requester_nf_type before calling
While going through the documentation it was found that string type should be used but while using it error was encountered.
Below is the code for reference

Python version - 3.8.10 

Code - 

  import openapi_client
  from com.h21lab.TS29510_Nnrf_NFDiscovery.model import nf_instances__store_api
  from openapi_client.model.nf_type import NFType
  from pprint import pprint
  configuration = openapi_client.Configuration(
      host = "http://localhost/nnrf-disc/v1"
  )
     with openapi_client.ApiClient(configuration) as api_client:
      api_instance = nf_instances__store_api.NFInstancesStoreApi(api_client)

      target_nf_type = NFType 
      requester_nf_type = NFType
       try:
          api_response = api_instance.search_nf_instances(target_nf_type, requester_nf_type)
          pprint(api_response)
       except openapi_client.ApiException as e:
          print("Exception when calling NFInstancesStoreApi->search_nf_instances: %s\n" % e)

Output-
Traceback (most recent call last):
  File "/home/developer/python/abc.py", line 16, in <module>
    api_response = api_instance.search_nf_instances(target_nf_type, requester_nf_type)
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 771, in __call__
    return self.callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/com/h21lab/TS29510_Nnrf_NFDiscovery/model/nf_instances__store_api.py", line 209, in __search_nf_instances
    return self.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 833, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 408, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 163, in __call_api
    query_params = self.sanitize_for_serialization(query_params)
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 284, in sanitize_for_serialization
    return [cls.sanitize_for_serialization(item) for item in obj]
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 284, in <listcomp>
    return [cls.sanitize_for_serialization(item) for item in obj]
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 284, in sanitize_for_serialization
    return [cls.sanitize_for_serialization(item) for item in obj]
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 284, in <listcomp>
    return [cls.sanitize_for_serialization(item) for item in obj]
  File "/usr/local/lib/python3.8/dist-packages/openapi_client/api_client.py", line 287, in sanitize_for_serialization
    raise ApiValueError('Unable to prepare type {} for serialization'.format(obj.__class__.__name__))
openapi_client.exceptions.ApiValueError: Unable to prepare type type for serialization

Any help would be appreciated.
Thanks in advance.

**Comment by H21lab** [comment]
If the scheme used by generator is correct according to OpenAPI specification, then it can be a limitation of the python generator. Such issues can be reported here https://github.com/OpenAPITools/openapi-generator/issues with prefix [BUG][PYTHON]. 

For workaround you can try to use different OpenAPI generator or try to modify the scheme in a way to satisfy the generator and to keep the serialized message the same. However this is not always possible. And the last resort, and definitively not the recommended way, could be to fix the generated code manually by hardcoding.
